export default {
  SETCONTENT: "SETCONTENT",
  NEWSETCONTENT: "NEWSETCONTENT",
  DELETECONTENT: "DELETECONTENT",
  SPLITCOLUMN: "SPLITCOLUMN",
  SPLITROW: "SPLITROW",
  JOINROW: "JOINROW",
  JOINCOLUMN: "JOINCOLUMN",
  SETFONT: "SETFONT",
  TEXTBOLD: "TEXTBOLD",
  REGULAR: "REGULAR",
};
